version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:vRIVqWvGdmSGKzRbyMCTubyNIfttfzGb@centerbeam.proxy.rlwy.net:59922/railway
    command: ["python", "main.py"]
